import Foundation

/// One event from the local service, decoded from the wire format in `src/vnr/events.py`.
///
/// Every envelope looks the same — `{"type", "session_id", "ts", "data"}` — and only the
/// `data` payload varies, so this decodes the envelope once and switches on the type.
///
/// **Unknown types decode to ``unknown`` rather than throwing.** The service is free to
/// add events; a UI built against an older copy must ignore them, not fall over. The
/// fixtures under `Tests/VNRKitTests/Fixtures` are generated by the Python suite
/// (`tests/test_event_contract.py`), which fails if they drift from what the service
/// actually emits.
public struct ServiceEvent: Equatable, Sendable {
    public let sessionID: String
    public let timestamp: Double
    public let kind: Kind

    public enum Kind: Equatable, Sendable {
        case asrPartial(text: String)
        case asrFinal(text: String)
        case asrError(code: String, message: String)

        case researchStarted(query: String)
        case searchStarted(index: Int, query: String, depth: String?)
        case searchCompleted(index: Int, query: String, resultCount: Int, error: String?)
        case synthesizing(sourceCount: Int)
        case answerDelta(text: String)
        case researchCompleted(Completion)
        case researchFailed(code: String, message: String)
        case researchCancelled

        case stateChanged(state: SessionState, ready: Bool?)

        /// An event type this build does not know about. Carried, not discarded, so it
        /// can be logged.
        case unknown(type: String)
    }

    /// A source the answer actually cited, numbered to match its `[n]` marker in the text.
    public struct Citation: Equatable, Sendable, Decodable {
        public let number: Int
        public let id: String
        public let title: String
        public let url: String
    }

    public struct Completion: Equatable, Sendable {
        public let turns: Int
        public let searches: Int
        public let sourceCount: Int
        public let citedSources: [Citation]
        public let invalidCitationIDs: [String]
        public let stopReason: String?
        public let tavilyCredits: Int?
        public let totalMilliseconds: Double?
    }
}

extension ServiceEvent: Decodable {
    private enum EnvelopeKey: String, CodingKey {
        case type, ts, data
        case sessionID = "session_id"
    }

    private enum DataKey: String, CodingKey {
        case text, code, message, query, index, error, turns, searches, metrics, state, ready
        case resultCount = "result_count"
        case searchDepth = "search_depth"
        case sourceCount = "source_count"
        case citedSources = "cited_sources"
        case invalidCitationIDs = "invalid_citation_ids"
        case stopReason = "stop_reason"
    }

    private typealias DataContainer = KeyedDecodingContainer<DataKey>

    public init(from decoder: Decoder) throws {
        let envelope = try decoder.container(keyedBy: EnvelopeKey.self)
        let type = try envelope.decode(String.self, forKey: .type)
        sessionID = (try? envelope.decode(String.self, forKey: .sessionID)) ?? ""
        timestamp = (try? envelope.decode(Double.self, forKey: .ts)) ?? 0

        // A missing or malformed `data` must not lose the event; the per-type decoding
        // below supplies defaults instead.
        let data = try? envelope.nestedContainer(keyedBy: DataKey.self, forKey: .data)
        kind = Self.decodeKind(type: type, data: data)
    }

    // MARK: - Lenient field access
    //
    // Every accessor tolerates a missing container, a missing key and a wrong type.
    // The UI showing a default beats the UI dropping the event.

    private static func string(
        _ data: DataContainer?, _ key: DataKey, _ fallback: String = ""
    ) -> String {
        optional(data, key, as: String.self) ?? fallback
    }

    private static func int(_ data: DataContainer?, _ key: DataKey, _ fallback: Int = 0) -> Int {
        optional(data, key, as: Int.self) ?? fallback
    }

    private static func optional<T: Decodable>(
        _ data: DataContainer?, _ key: DataKey, as type: T.Type
    ) -> T? {
        guard let data else { return nil }
        return try? data.decode(T.self, forKey: key)
    }

    // MARK: - Per-type payloads

    private static func decodeKind(type: String, data: DataContainer?) -> Kind {
        switch type {
        case "asr.partial":
            return .asrPartial(text: string(data, .text))
        case "asr.final":
            return .asrFinal(text: string(data, .text))
        case "asr.error":
            return .asrError(code: string(data, .code), message: string(data, .message))

        case "research.started":
            return .researchStarted(query: string(data, .query))
        case "research.search_started":
            return .searchStarted(
                index: int(data, .index),
                query: string(data, .query),
                depth: optional(data, .searchDepth, as: String.self)
            )
        case "research.search_completed":
            return .searchCompleted(
                index: int(data, .index),
                query: string(data, .query),
                resultCount: int(data, .resultCount),
                error: optional(data, .error, as: String.self)
            )
        case "research.synthesizing":
            return .synthesizing(sourceCount: int(data, .sourceCount))
        case "research.answer_delta":
            return .answerDelta(text: string(data, .text))
        case "research.completed":
            return .researchCompleted(completion(data))
        case "research.failed":
            return .researchFailed(code: string(data, .code), message: string(data, .message))
        case "research.cancelled":
            return .researchCancelled

        case "session.state_changed":
            return .stateChanged(
                state: SessionState(wireName: string(data, .state)),
                ready: optional(data, .ready, as: Bool.self)
            )

        default:
            return .unknown(type: type)
        }
    }

    private static func completion(_ data: DataContainer?) -> Completion {
        let metrics = optional(data, .metrics, as: Metrics.self)
        return Completion(
            turns: int(data, .turns),
            searches: int(data, .searches),
            sourceCount: int(data, .sourceCount),
            citedSources: optional(data, .citedSources, as: [Citation].self) ?? [],
            invalidCitationIDs: optional(data, .invalidCitationIDs, as: [String].self) ?? [],
            stopReason: optional(data, .stopReason, as: String.self),
            tavilyCredits: metrics?.tavilyCredits,
            totalMilliseconds: metrics?.goToCompletedMs
        )
    }

    private struct Metrics: Decodable {
        let tavilyCredits: Int?
        let goToCompletedMs: Double?

        enum CodingKeys: String, CodingKey {
            case tavilyCredits = "tavily_credits"
            case goToCompletedMs = "go_to_completed_ms"
        }
    }

    /// Decode one event from a WebSocket text frame.
    public static func decode(from json: Foundation.Data) throws -> ServiceEvent {
        try JSONDecoder().decode(ServiceEvent.self, from: json)
    }
}
