import XCTest
@testable import VNRKit

/// Decoding is checked against fixtures generated by the Python suite
/// (`tests/test_event_contract.py`), so these assertions describe what the service
/// really emits rather than what this file imagines it emits.
final class ServiceEventTests: XCTestCase {
    private struct Fixture: Decodable {
        let label: String
        let json: String
    }

    private func fixtures() throws -> [Fixture] {
        let url = try XCTUnwrap(
            Bundle.module.url(forResource: "events", withExtension: "json", subdirectory: "Fixtures"),
            "events.json is missing — regenerate with "
                + "VNR_UPDATE_FIXTURES=1 uv run pytest tests/test_event_contract.py"
        )
        return try JSONDecoder().decode([Fixture].self, from: Data(contentsOf: url))
    }

    private func event(_ label: String, at occurrence: Int = 0) throws -> ServiceEvent {
        let matching = try fixtures().filter { $0.label == label }
        let fixture = try XCTUnwrap(
            matching.dropFirst(occurrence).first,
            "no fixture labelled \(label) at occurrence \(occurrence)"
        )
        return try ServiceEvent.decode(from: Data(fixture.json.utf8))
    }

    // MARK: - Every fixture decodes

    func testEveryFixtureDecodes() throws {
        let all = try fixtures()
        XCTAssertFalse(all.isEmpty)
        for fixture in all {
            XCTAssertNoThrow(
                try ServiceEvent.decode(from: Data(fixture.json.utf8)),
                "failed to decode \(fixture.label)"
            )
        }
    }

    func testEnvelopeFieldsAreCarried() throws {
        let decoded = try event("asr.partial")
        XCTAssertEqual(decoded.sessionID, "fixture0001")
        XCTAssertEqual(decoded.timestamp, 0)
    }

    // MARK: - Speech

    func testAsrPartialAndFinal() throws {
        guard case .asrPartial(let partial) = try event("asr.partial").kind else {
            return XCTFail("expected asrPartial")
        }
        XCTAssertEqual(partial, "find recent work on streaming")

        guard case .asrFinal(let final) = try event("asr.final").kind else {
            return XCTFail("expected asrFinal")
        }
        XCTAssertEqual(final, "find recent work on streaming ASR for Darija")
    }

    func testAsrErrorCarriesTheReason() throws {
        guard case .asrError(let code, let message) = try event("asr.error").kind else {
            return XCTFail("expected asrError")
        }
        XCTAssertEqual(code, "microphone")
        XCTAssertTrue(message.contains("silence"))
    }

    // MARK: - Research progress

    func testSearchStartedCarriesTheDepthWhenPresent() throws {
        guard case .searchStarted(let index, let query, let depth) =
            try event("research.search_started").kind
        else { return XCTFail("expected searchStarted") }
        XCTAssertEqual(index, 1)
        XCTAssertEqual(query, "streaming ASR low-resource languages")
        XCTAssertEqual(depth, "advanced")
    }

    func testSearchCompletedSucceeded() throws {
        guard case .searchCompleted(_, _, let count, let error) =
            try event("research.search_completed").kind
        else { return XCTFail("expected searchCompleted") }
        XCTAssertEqual(count, 5)
        XCTAssertNil(error, "a successful search must not carry an error")
    }

    func testSearchCompletedFailed() throws {
        guard case .searchCompleted(_, _, let count, let error) =
            try event("research.search_completed", at: 1).kind
        else { return XCTFail("expected searchCompleted") }
        XCTAssertEqual(count, 0)
        XCTAssertEqual(error, "tavily_rate_limit")
    }

    func testAnswerDelta() throws {
        guard case .answerDelta(let text) = try event("research.answer_delta").kind else {
            return XCTFail("expected answerDelta")
        }
        XCTAssertEqual(text, "Kyutai streams audio [1].")
    }

    // MARK: - Completion

    func testCompletionCarriesClickableCitations() throws {
        guard case .researchCompleted(let completion) =
            try event("research.completed").kind
        else { return XCTFail("expected researchCompleted") }

        XCTAssertEqual(completion.turns, 3)
        XCTAssertEqual(completion.searches, 2)
        XCTAssertEqual(completion.sourceCount, 5)
        XCTAssertEqual(completion.stopReason, "evidence_sufficient")
        XCTAssertEqual(completion.tavilyCredits, 2)
        XCTAssertEqual(completion.totalMilliseconds, 9720.4)
        XCTAssertEqual(completion.invalidCitationIDs, ["S42"])

        // The numbers must match the [n] markers in the answer text.
        XCTAssertEqual(completion.citedSources.count, 1)
        let citation = try XCTUnwrap(completion.citedSources.first)
        XCTAssertEqual(citation.number, 1)
        XCTAssertEqual(citation.id, "S1")
        XCTAssertEqual(citation.url, "https://kyutai.org/stt")
    }

    func testFailureAndCancellation() throws {
        guard case .researchFailed(let code, let message) = try event("research.failed").kind
        else { return XCTFail("expected researchFailed") }
        XCTAssertEqual(code, "nebius_auth")
        XCTAssertFalse(message.isEmpty)

        guard case .researchCancelled = try event("research.cancelled").kind else {
            return XCTFail("expected researchCancelled")
        }
    }

    // MARK: - Forward compatibility

    func testAnUnknownEventTypeIsCarriedNotThrown() throws {
        guard case .unknown(let type) = try event("research.future_thing").kind else {
            return XCTFail("an unrecognised event must decode to .unknown")
        }
        XCTAssertEqual(type, "research.future_thing")
    }

    func testAMissingDataPayloadDoesNotLoseTheEvent() throws {
        let decoded = try ServiceEvent.decode(from: Data(#"{"type": "asr.partial"}"#.utf8))
        guard case .asrPartial(let text) = decoded.kind else {
            return XCTFail("expected asrPartial")
        }
        XCTAssertEqual(text, "", "a missing payload should default, not throw")
    }

    func testAWronglyTypedFieldFallsBackInsteadOfThrowing() throws {
        let json = #"{"type": "research.synthesizing", "data": {"source_count": "five"}}"#
        guard case .synthesizing(let count) = try ServiceEvent.decode(from: Data(json.utf8)).kind
        else { return XCTFail("expected synthesizing") }
        XCTAssertEqual(count, 0)
    }
}

final class SessionStateTests: XCTestCase {
    func testWireNamesMapToStates() throws {
        XCTAssertEqual(SessionState(wireName: "REVIEW"), .review)
        XCTAssertEqual(SessionState(wireName: "ANSWER_STREAMING"), .answerStreaming)
        XCTAssertEqual(SessionState(wireName: "WAT"), .unknown("WAT"))
    }

    func testStateChangedFixtureDecodes() throws {
        let json = #"{"type": "session.state_changed", "data": {"state": "LISTENING"}}"#
        guard case .stateChanged(let state, let ready) =
            try ServiceEvent.decode(from: Data(json.utf8)).kind
        else { return XCTFail("expected stateChanged") }
        XCTAssertEqual(state, .listening)
        XCTAssertNil(ready)
    }

    func testTheOpeningEventCarriesReadiness() throws {
        let json = #"{"type": "session.state_changed", "data": {"state": "IDLE", "ready": false}}"#
        guard case .stateChanged(_, let ready) =
            try ServiceEvent.decode(from: Data(json.utf8)).kind
        else { return XCTFail("expected stateChanged") }
        XCTAssertEqual(ready, false, "the record button is gated on this")
    }

    func testRecordingIsOnlyOfferedInSettledStates() {
        XCTAssertTrue(SessionState.idle.acceptsNewRecording)
        XCTAssertTrue(SessionState.completed.acceptsNewRecording)
        XCTAssertTrue(SessionState.failed.acceptsNewRecording)
        XCTAssertFalse(SessionState.listening.acceptsNewRecording)
        XCTAssertFalse(SessionState.synthesizing.acceptsNewRecording)
    }

    func testResearchInFlight() {
        XCTAssertTrue(SessionState.answerStreaming.isResearching)
        XCTAssertFalse(SessionState.review.isResearching)
    }
}
